freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  auto_cancellation: $CI != "true"
  install_script:
    - sudo tzsetup America/New_York
    - sudo pkg install -y p5-Dist-Zilla p5-App-cpanminus git libffi p5-Capture-Tiny p5-ExtUtils-MakeMaker p5-IPC-Cmd p5-ExtUtils-ParseXS pkgconf
    - sudo dzil authordeps --missing | cpanm -n
    - sudo dzil listdeps --missing | cpanm -n
  script:
    - dzil test -v
  
