#!/bin/sh

if echo $CIP_ENV | grep -q FFI_PLATYPUS_TEST_EXAMPLES ; then 

  dir=$(ls -1d FFI-Platypus-* | grep -v tar.gz)
  cip sudo apt-get install libtcod1 libnotify4 libzmq5
  cip exec cpanm -n Capture::Tiny Test::Script Path::Tiny Convert::Binary::C YAML File::chdir Alien::Libbz2 FFI::Platypus FFI::C
  cip exec bash -c "cd $dir && prove -vm xt/author/example.t"

fi
