#!/bin/bash

set -ex

perl Build.PL
cpanm --installdeps .
./Build
./Build test verbose=1
./Build install

if perl -e 'exit ! ($] > 5.010)'; then

  cpanm -n local::lib

  maint/cip-test-cpan FFI::Util
  maint/cip-test-cpan FFI::TinyCC
  maint/cip-test-cpan FFI::TinyCC::Inline
  maint/cip-test-cpan FFI::ExtractSymbols
  
  maint/cip-test-cpan UUID::FFI
  maint/cip-test-cpan Acme::Ford::Prefect::FFI
  maint/cip-test-cpan File::LibMagic::FFI
  cpanm -n Math::BigInt

  maint/cip-test-cpan FFI::Platypus::Lang::CPP
  maint/cip-test-cpan FFI::Platypus::Lang::Fortran
  maint/cip-test-cpan FFI::Platypus::Lang::Pascal
  cpanm -n Test::Script IPC::Run3
  maint/cip-test-cpan FFI::Platypus::Lang::Rust

  ##cpanm -n Convert::Binary::C
  ##perl inc/run/test_examples.pl

fi
