#!/bin/bash

set -ex

cip sudo apt-get update
cip sudo apt-get install gfortran-6 fp-compiler-3.0.0 g++ libgtop-2.0-10 libffi-dev libmagic-dev
cip exec cpanm -n version

# we want to do this maybe in just one run or something
#cip exec cpanm -n Acme::Alien::DontPanic
cip exec cpanm -n Math::LongDouble

if [ "$CIP_TAG" == "5.30-debug" ]; then
  cip exec cpanm -n Test::LeakTrace
fi
