#!/bin/bash

set -ex

make
make test TEST_VERBOSE=1
make install

if [ "$FFI_PLATYPUS_NO_EXTRA_TYPES" = "1" ]; then
  exit 0;
fi;

if perl -e 'exit ! ($] > 5.016)'; then

  cpanm -n local::lib

  maint/cip-test-cpan FFI::Util
  maint/cip-test-cpan FFI::ExtractSymbols

  maint/cip-test-cpan UUID::FFI
  maint/cip-test-cpan Acme::Ford::Prefect::FFI
  maint/cip-test-cpan File::LibMagic::FFI
  cpanm -n Math::BigInt

  maint/cip-test-cpan FFI::Platypus::Lang::CPP
  maint/cip-test-cpan FFI::Platypus::Lang::Fortran
  maint/cip-test-cpan FFI::Platypus::Lang::Pascal
  cpanm -n Test::Script IPC::Run3

  ##cpanm -n Convert::Binary::C
  ##perl maint/cip-test-examples

fi
