use strict;
use warnings;
use autodie qw( :all );

my $content;

open my $in, '<', 'Build.PL';
while(<$in>)
{
  s/^(# This file was automatically generated by Dist::Zilla::Plugin::ModuleBuild).*$/$1/;
  $content .= $_;
}
close $in;

open my $out, '>', 'Build.PL';
print $out $content;
close $out;
