name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        cip:
          - tag: "5.41"
          - tag: "5.40"
          - tag: "5.40"
            env: FFI_PLATYPUS_MEMORY_STRDUP_IMPL=ffi
          - tag: "5.40"
            env: FFI_PLATYPUS_TEST_EXAMPLES=1
          - tag: "5.40"
            env: FFI_PLATYPUS_NO_ALLOCA=1
          - tag: "5.40"
            env: FFI_PLATYPUS_NO_EXTRA_TYPES=1
          - tag: "5.40"
            env: FFI_PLATYPUS_PROBE_OVERRIDE=variadic=0
          - tag: "5.40-bullseye32"
          - tag: "5.36-debug"
          - tag: "5.36-debug32"
          - tag: "5.40-ffimaster"
          - tag: "5.40-longdouble"
          - tag: "5.40-quadmath"
          - tag: "5.40-threads"
          - tag: "5.38"
          - tag: "5.36"
          - tag: "5.34"
          - tag: "5.32"
          - tag: "5.30"
          - tag: "5.28"
          - tag: "5.26"
          - tag: "5.24"
          - tag: "5.22"
          - tag: "5.20"
          - tag: "5.18"
          - tag: "5.16"
          - tag: "5.14"
          - tag: "5.14-longdouble"
          - tag: "5.12"
          - tag: "5.10"
          - tag: "5.8.9"
          - tag: "5.8.8"
          - tag: "5.8.4"

    env:
      CIP_TAG: ${{ matrix.cip.tag }}
      CIP_ENV: ${{ matrix.cip.env }}

    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap CIP
        run: |
          curl -L https://raw.githubusercontent.com/uperl/cip/main/bin/github-bootstrap | bash

      - name: Cache-Key
        id: cache-key
        run: |
          echo -n '::set-output name=key::'
          cip cache-key

      - name: Cache CPAN modules
        uses: actions/cache@v2
        with:
          path: ~/.cip
          key: ${{ runner.os }}-build-${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-build-${{ steps.cache-key.outputs.key }}

      - name: Start-Container
        run: |
          cip start

      - name: Diagnostics
        run: |
          cip diag

      - name: Install-Dependencies
        run: |
          cip install

      - name: Build + Test
        run: |
          cip script

      - name: Test Examples
        run: |
          ./maint/cip-test-examples

      - name: CPAN log
        if: ${{ failure() }}
        run: |
          cip exec bash -c 'cat $HOME/.cpanm/latest-build/build.log'
